import html
import os
from datetime import datetime, timezone

from YST_lib.dashboard import METRIC_LABELS, format_number

CHART_KEYS = ("video_views", "video_likes", "video_comments", "subs", "channel_views")

HEX_COLORS = {
    "video_views": "#d7a800",
    "video_likes": "#af52de",
    "video_comments": "#ff5f56",
    "subs": "#2ecc71",
    "channel_views": "#2fb5c4",
}

WIDTH = 720
HEIGHT = 220
PADDING = 40


def _escape(value):
    return html.escape(str(value), quote=True)


def _points(values):
    if len(values) < 2:
        return ""
    low, high = min(values), max(values)
    span = high - low or 1
    step = (WIDTH - 2 * PADDING) / (len(values) - 1)
    coordinates = []
    for index, value in enumerate(values):
        x = PADDING + index * step
        y = HEIGHT - PADDING - (value - low) / span * (HEIGHT - 2 * PADDING)
        coordinates.append(f"{x:.1f},{y:.1f}")
    return " ".join(coordinates)


def _chart(key, points):
    if len(points) < 2:
        return ""
    values = [value for _, value in points]
    low, high = min(values), max(values)
    path = _points(values)
    color = HEX_COLORS.get(key, "#666666")
    label = _escape(METRIC_LABELS.get(key, key))
    return f"""
    <section class="chart">
      <h3>{label}</h3>
      <svg viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-label="{label} over time">
        <polyline fill="none" stroke="{color}" stroke-width="2" points="{path}" />
      </svg>
      <p class="range">{_escape(format_number(low))} &rarr; {_escape(format_number(high))}
        <span>{len(values)} snapshots</span></p>
    </section>"""


def _table(rows, keys):
    header = "".join(f"<th>{_escape(METRIC_LABELS.get(key, key))}</th>" for key in keys)
    body = []
    for row in rows:
        cells = [f"<td>{_escape(row['recorded_at'])}</td>"]
        cells += [f"<td>{_escape(format_number(row.get(key, 0)))}</td>" for key in keys]
        body.append("<tr>" + "".join(cells) + "</tr>")
    return f"""
    <table>
      <thead><tr><th>Recorded at</th>{header}</tr></thead>
      <tbody>{''.join(body)}</tbody>
    </table>"""


def render_report(rows, samples, channel_id, video_id, hours, generated=None):
    stamp = generated or datetime.now(timezone.utc).strftime("%d-%m-%Y %H:%M UTC")
    charts = "".join(_chart(key, samples.get(key, [])) for key in CHART_KEYS)
    keys = [key for key in CHART_KEYS if any(key in row for row in rows)]
    title = f"YouTube Stats report — {channel_id}"
    if video_id:
        title += f" / {video_id}"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_escape(title)}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font: 15px/1.5 system-ui, sans-serif; margin: 0 auto; max-width: 800px; padding: 2rem 1rem; }}
  h1 {{ font-size: 1.4rem; margin-bottom: .25rem; }}
  .meta {{ opacity: .7; margin-top: 0; }}
  .charts {{ display: grid; gap: 1.5rem; }}
  .chart h3 {{ font-size: 1rem; margin: 0 0 .25rem; }}
  .chart svg {{ width: 100%; height: auto; background: rgba(127,127,127,.08); border-radius: 6px; }}
  .range {{ opacity: .7; font-size: .85rem; margin: .25rem 0 0; }}
  .range span {{ opacity: .7; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 2rem; font-size: .9rem; }}
  th, td {{ border-bottom: 1px solid rgba(127,127,127,.3); padding: .35rem .5rem; text-align: right; }}
  th:first-child, td:first-child {{ text-align: left; }}
  footer {{ margin-top: 2rem; opacity: .6; font-size: .8rem; }}
</style>
</head>
<body>
<h1>{_escape(title)}</h1>
<p class="meta">Last {hours} hours &middot; generated {_escape(stamp)}</p>
<div class="charts">{charts}</div>
{_table(rows[-200:], keys)}
<footer>Generated by YouTube Stats Tool (YST)</footer>
</body>
</html>
"""


def save_report(content, folder="exports", name="report.html"):
    os.makedirs(folder, exist_ok=True)
    target = f"{folder}/{name}"
    try:
        with open(target, "w", encoding="utf-8") as f:
            f.write(content)
    except OSError as e:
        raise OSError(f"Cannot write '{target}': {e}") from e
    return target
